name: On Push

on:
    push:
      branches:
        - master
        - main
        - develop
        - release/*
      paths-ignore:
        - 'readme.md'
        - 'CHANGELOG.md'
        - 'docs/**'

env:
    DOTNET_VERSION: '7.0.x'


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              env:
                shuai_secret: ${{ secret.SHUAI_ENV_SECRET}}
              run: |
                echo "$shuai_secret"
        # steps:
        #   - name: test1
        #     uses: actions/setup-dotnet@v3
        #     with: 
        #         shuai_secret: ${{ secret.ShuaiSecret}}
        #     run : echo "$shuai_secret"
