name: On Push

on:
    push:
      branches:
        - master
        - main
        - develop
        - release/*
      paths-ignore:
        - 'readme.md'
        - 'CHANGELOG.md'
        - 'docs/**'

env:
    DOTNET_VERSION: '7.0.x'
    PUSH_ON_MASTET: ${{github.event_name == 'push' && github.ref == 'refs/heads/master'}}


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              env:
                shuai_secret: ${{ secrets.SHUAI_ENV_SECRET }}
                shuai_repo_secret: ${{ secrets.SHUAI_REPO_SECRET }}
              run: |
                echo "Hello world!"
                echo $shuai_secret
                echo $shuai_repo_secret
            - name: Set Conditon to Env
              run: |
                if ${PUSH_ON_MASTET} == true; then
                  echo "flag=true" >> $GITHUB_ENV
                  echo "flag set to true"
                else
                  echo "flag=false" >> $GITHUB_ENV
                  echo "flag set to false"
                fi
            - name: test1
            #   uses: actions/setup-dotnet@v3
              env:
                shuai_secret: ${{ secrets.SHUAI_REPO_SECRET}}
              if: ${{env.PUSH_ON_MASTET=='true'}}
              run : |
                echo ${{env.PUSH_ON_MASTET}}
                echo "shuai_secret: $shuai_secret"
            - name: test2
              if: env.flag
              run: |
                echo "test2:${{env.flag}}"
