name: On Push

on:
    push:
      branches:
        - master
        - main
        - develop
        - release/*
      paths-ignore:
        - 'readme.md'
        - 'CHANGELOG.md'
        - 'docs/**'

env:
    DOTNET_VERSION: '7.0.x'


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              env:
                shuai_secret: ${{ secrets.SHUAI_ENV_SECRET }}
                shuai_repo_secret: ${{ secrets.SHUAI_REPO_SECRET }}
              run: |
                echo "Hello world!"
                echo $shuai_secret
                echo $shuai_repo_secret
            - name: test1
            #   uses: actions/setup-dotnet@v3
              env:
                shuai_secret: ${{ secrets.SHUAI_REPO_SECRET}}
              run : |
                echo "shuai_secret: $shuai_secret"
